name: "Pilot Bot"
version: "1.0.0"
slug: "pilot_discord_bot"
description: "Personal Discord bot."
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  bot_token: ""
  chutes_api_key: ""
  chutes_model: "deepseek-ai/DeepSeek-V3-0324"
  pilot_history_limit: 300
  pilot_response_channel_id: ""
  pilot_enabled: false
schema:
  bot_token: "password"
  chutes_api_key: "password"
  chutes_model: "str"
  pilot_history_limit: "int"
  pilot_response_channel_id: "str?"
  pilot_enabled: "bool"
